// category
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// ui
export const TOGGLE_RIGHT_DRAWER = "TOGGLE_RIGHT_DRAWER";
export const TOGGLE_LEFT_DRAWER = "TOGGLE_LEFT_DRAWER";
