// todolist
export const RETRIEVE_TODO_LIST = "RETRIEVE_TODO_LIST";
export const GET_ALL_TODOS_BY_DATE = "GET_ALL_TODOS_BY_DATE";
export const SAVE_TODO = "SAVE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const SELECT_TODO = "SELECT_TODO";

// sticky
export const RETRIEVE_STICKIES = "RETRIEVE_STICKIES";
export const SAVE_STICKY = "SAVE_STICKY";
export const DELETE_STICKY = "DELETE_STICKY";

// category
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// ui
export const TOGGLE_RIGHT_DRAWER = "TOGGLE_RIGHT_DRAWER";
export const TOGGLE_LEFT_DRAWER = "TOGGLE_LEFT_DRAWER";
